# Generated by Django 2.2.16 on 2020-10-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCar', '0004_misionyvision_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misionyvision',
            name='numero',
        ),
    ]
